-- MySQL Script generated by MySQL Workbench
-- 02/20/19 11:37:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SolicitudRenovacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SolicitudRenovacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SolicitudRenovacion` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `SolicitudRenovacion` ;

-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_AcreditaDomicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_AcreditaDomicilio` (
  `id_acredita` INT NOT NULL AUTO_INCREMENT,
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_acredita`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_Persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `rut_persona` VARCHAR(12) NOT NULL,
  `nombre_persona` VARCHAR(40) NOT NULL,
  `apellidoP_persona` VARCHAR(50) NOT NULL,
  `apellidoM_persona` VARCHAR(50) NOT NULL,
  `fechaNacimiento_persona` DATE NOT NULL,
  `sexo_persona` ENUM('No Especifica', 'Femenino', 'Masculino') NOT NULL DEFAULT 'No Especifica',
  `telefono_persona` VARCHAR(12) NOT NULL,
  `correo_persona` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `rut_persona_UNIQUE` (`rut_persona` ASC),
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_Licencia` (
  `id_licencia` INT NOT NULL AUTO_INCREMENT,
  `clase_licencia` ENUM('A1', 'A2', 'A3', 'A4', 'A5', 'B', 'C', 'D', 'A1-A2 Ley 18.290') NOT NULL,
  `comunaOrigen_licencia` VARCHAR(100) NOT NULL,
  `fechaControl_licencia` DATE NOT NULL,
  PRIMARY KEY (`id_licencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_Direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `ciudad_dir` VARCHAR(50) NOT NULL DEFAULT 'Santiago',
  `comuna_dir` VARCHAR(50) NOT NULL DEFAULT 'Padre Hurtado',
  `villaPoblacion_dir` VARCHAR(100) NOT NULL,
  `blockParcelaEdificio` VARCHAR(45) NOT NULL COMMENT 'INSERT INTO `SolicitudRenovacion`.`TA_Persona` (`rut_persona`, `nombre_persona`, `apellidoP_persona`, `apellidoM_persona`, `fechaNacimiento_persona`, `FKSexo_id_sexo`, `FKTelefono_id_telefono`, `FKDireccion_id_direccion`, `PKCorreo_id_correo`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);',
  `numero_dir` INT NOT NULL,
  `FKid_persona` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_TA_Direccion_TA_Persona1_idx` (`FKid_persona` ASC),
  CONSTRAINT `fk_TA_Direccion_TA_Persona1`
    FOREIGN KEY (`FKid_persona`)
    REFERENCES `SolicitudRenovacion`.`TA_Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_Horario` (
  `id_hora` INT NOT NULL AUTO_INCREMENT,
  `fecha_horario` DATE NOT NULL,
  `hora_horario` TIME NOT NULL,
  PRIMARY KEY (`id_hora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_SolicitudRenovacionLicencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_SolicitudRenovacionLicencia` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `FKrut_persona` VARCHAR(12) NOT NULL,
  `FKid_acredita` INT NOT NULL,
  `FKid_hora` INT NOT NULL,
  `FKLicencia_id_licencia` INT NOT NULL,
  `estado_solicitud` ENUM('Pendiente', 'Aprobada', 'Rechazada') NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_TA_SolicitudRenovacionLicencia_TA_Persona1_idx` (`FKrut_persona` ASC),
  INDEX `fk_TA_SolicitudRenovacionLicencia_TA_AcreditaDomicilio1_idx` (`FKid_acredita` ASC),
  INDEX `fk_TA_SolicitudRenovacionLicencia_TA_Horario1_idx` (`FKid_hora` ASC),
  INDEX `fk_TA_SolicitudRenovacionLicencia_TA_Licencia1_idx` (`FKLicencia_id_licencia` ASC),
  CONSTRAINT `fk_TA_SolicitudRenovacionLicencia_TA_Persona1`
    FOREIGN KEY (`FKrut_persona`)
    REFERENCES `SolicitudRenovacion`.`TA_Persona` (`rut_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TA_SolicitudRenovacionLicencia_TA_AcreditaDomicilio1`
    FOREIGN KEY (`FKid_acredita`)
    REFERENCES `SolicitudRenovacion`.`TA_AcreditaDomicilio` (`id_acredita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TA_SolicitudRenovacionLicencia_TA_Horario1`
    FOREIGN KEY (`FKid_hora`)
    REFERENCES `SolicitudRenovacion`.`TA_Horario` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TA_SolicitudRenovacionLicencia_TA_Licencia1`
    FOREIGN KEY (`FKLicencia_id_licencia`)
    REFERENCES `SolicitudRenovacion`.`TA_Licencia` (`id_licencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `SolicitudRenovacion`.`TA_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SolicitudRenovacion`.`TA_Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `rut_usuario` VARCHAR(12) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `correo_usuario` VARCHAR(70) NOT NULL,
  `pass_usuario` VARCHAR(255) NOT NULL,
  `tipo_usuario` ENUM('Funcionario', 'Administrador', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_usuario_UNIQUE` (`correo_usuario` ASC),
  UNIQUE INDEX `rut_usuario_UNIQUE` (`rut_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
